files:
  include: "src/static/stylesheets/*.scss"
  ignore:
    - "src/static/stylesheets/fonts.scss"
rules:
  leading-zero:
  - 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  quotes:
  - 1
  - style: double
