files:
  include: "lib/static/stylesheets/*.scss"
  ignore:
    - "lib/static/stylesheets/reset.module.scss"
rules:
  no-color-literals:
    - 0
  class-name-format:
    - 2
    - convention: hyphenatedbem
  leading-zero:
  - 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  quotes:
  - 1
  - style: double
  no-vendor-prefixes:
  - 0
